version: '1.0'
context:
  type: text
  source:
    content: "Ad: Ahmet Yılmaz\nDoğum Tarihi: 01 Ocak 1990\nE-posta: ahmet.yilmaz@example.com\n\
      \nEğitim:\n- Lisans: Bilgisayar Mühendisliği, Boğaziçi Üniversitesi, 2008-2012\n\
      - Yüksek Lisans: Veri Bilimi, İstanbul Teknik Üniversitesi, 2013-2015\n\nİş\
      \ Deneyimi:\n- Yazılım Mühendisi, ABC Teknoloji, 2012-2015\n  * Web uygulamaları\
      \ geliştirme\n  * Veritabanı yönetimi\n- Kıdemli Veri Bilimci, XYZ Şirketi,\
      \ 2016-2020\n  * Makine öğrenimi modelleri geliştirme\n  * Büyük veri analitiği\n\
      - Teknik Lider, DEF Startup, 2021-Halen\n  * Ekip yönetimi\n  * Bulut tabanlı\
      \ çözümler geliştirme\n\nBeceriler:\n- Python, Java, SQL\n- Makine Öğrenimi,\
      \ Veri Analizi\n- AWS, Docker"
metadata:
  description: Özgeçmiş içeriği
  created_at: '2025-06-25'
  language: tr
